services:
  cuncord:
    container_name: cuncord_bot
    image: cuncord
    environment:
      DISCORD_TOKEN: "TOKEN"
      DISCORD_CLIENT_ID: "CLIENT"
      DISCORD_GUILD_ID: "GUILD"
    restart: unless-stopped
    tty: true
    volumes: 
      - "audio:audio"
